;;; darktooth-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from darktooth.el

(autoload 'darktooth-deftheme "darktooth" "\
Create darktooth theme with NAME, DESCRIPTION, PALETTE and BODY.

(fn NAME DESCRIPTION PALETTE &rest BODY)" nil t)
(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))


;;; Generated autoloads from darktooth-dark-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "darktooth-dark-theme" '("darktooth-modeline"))


;;; Generated autoloads from darktooth-darker-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "darktooth-darker-theme" '("darktooth-modeline"))


;;; Generated autoloads from darktooth-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "darktooth-theme" '("darktooth-modeline"))

;;; End of scraped data

(provide 'darktooth-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; darktooth-theme-autoloads.el ends here
